config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  root 'welcome#index'
  get '/user' => "users#show", :as => :user_root
  resources :books, :except => [:destroy]
  post 'new_book', to: 'books#new'
  get 'external', to: 'books#external'
  resources :groups, :except => [:edit, :update, :destroy]
  resources :books_search
  get 'goodreads', to: 'books_search#index'
  get 'result', to: 'books_search#results'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_groups
  has_many :groups, through: :book_groups
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :author, presence: true, length: { minimum: 3, maximum: 30 }
  validates :number_of_pages, presence: true
  validates :description, presence: true, length: { minimum: 10, maxmimum: 300 }
  mount_uploader :image, ImageUploader
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/book_group.rb
class BookGroup < ApplicationRecord
  belongs_to :book
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :book_groups
  has_many :books, through: :book_groups
  belongs_to :user
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :name
  scope :ordered_alphabetically, -> { order(name: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { minimum: 3, maximum: 50 }
  validates :username, uniqueness: true
  has_many :books
  has_many :groups
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username image])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username image])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update]
  def index
    @user = current_user
    @books = Book.where(user: current_user).includes([:groups]).ordered_by_most_recent
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully added'
      redirect_to @book
    else
      flash.now[:alert] = 'something went wrong. Please double-check that you have filled in all the required fields'
      render 'new'
    end
  end

  def external
    @books = Book.where(user: User.where.not(id: current_user.id)).includes([:groups]).ordered_by_most_recent
  end

  def show; end

  def edit; end

  def update
    @book.update(book_params)
    if @book.save
      flash[:notice] = "#{@book.title} successfully edited"
      redirect_to @book
    else
      render 'edit'
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :number_of_pages, :image, :description, group_ids: [])
  end
end

app/controllers/books_search_controller.rb
class BooksSearchController < ApplicationController
  before_action :set_client, only: %i[index results]

  def index; end

  def results
    @search_raw = @client.search_books(search_params)

    if @search_raw.query == '' || @search_raw.results_end == '0'
      flash[:alert] = 'Something went wrong'
    elsif @search_raw.results.first[1].count == 9
      @unique_result = @search_raw
    else
      @multi_results = @search_raw
    end
    render :_results
  end

  private

  def set_client
    @client = Goodreads::Client.new(api_key: ENV['GOODREADS_API_KEY'], api_secret: ENV['GOODREADS_API_SECRET_KEY'])
  end

  def search_params
    params[:search]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show]

  def index
    @user = current_user
    @groups = Group.where(user: current_user).ordered_alphabetically
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      flash[:notice] = 'You have made a new group'
      redirect_to @group
    else
      flash.now[:alert] = 'something went wrong'
      render 'new'
    end
  end

  def show
    @books = @group.books
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    if @user.save
      sign_in @user
      redirect_to users_show_path
    else
      render 'devise/registrations/new'
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    redirect_to users_show_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in
    if current_user
      render 'layouts/usernav'
    else
      render 'layouts/navigation'
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_user
    render 'opinion' if @book.user == current_user
  end

  def book_edit
    render 'bookedit' if @book.user == current_user
  end
end

app/helpers/books_search_helper.rb
module BooksSearchHelper
  def search_results
    if @multi_results
      render 'multi'
    else
      render 'unique'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def book_group
    render @book.groups if @book.groups.any?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_avatar(user)
    if @user.image_url.nil?
      image_tag('default.jpeg', alt: user.username, class: 'avatar')
    else
      image_tag(@user.image.url, alt: user.username, class: 'avatar')
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_bookedit.html.erb
<small> 
  <%= link_to edit_book_path(@book), class: 'text-muted' do %>
	  <%= fa_icon "cog" %> Edit book
  <% end %>
</small>

app/views/books/_opinion.html.erb
<% if @book.user == current_user%>
    <p class="card-text  text-muted "> <strong> Personal Opinions:</strong>  <%= @book.description %> </p>
<% end %>

app/views/books/edit.html.erb
<div class="nav">
  <%= signed_in %>
  <h2 class="text-white center-nav">Edit <%= @book.title %></h2>
</div>

<div class="col-7 mx-auto py-5">

  <%= render 'layouts/messages'%>


  <%= form_with(model: @book, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder:'Title of Book', class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, placeholder:'Name of Author', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :number_of_pages %>
      <%= f.text_field :number_of_pages, placeholder:'Number of pages', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, placeholder:'Thoughts on this book?', class: 'form-control' %>
    </div>

    <div class="form-group row">
      <%= f.label :groups, class:"col-2 col-form-label"%>
      <div class="col-10">
        <%= f.collection_check_boxes :group_ids, Group.where(user: current_user), :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "mx-3 checkbox  shadow rounded") + cb.text } %>
        <% end %> 
      </div>      
    </div>
  
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <%= f.submit 'Edit Book', class: 'btn btn-success' %>
    </div>
  <% end %>
 </div>

app/views/books/external.html.erb
<div class="nav container-fluid h-100vh">
    <%= signed_in %>
    <h3 class="text-white center-nav"> Books other users are loving </h3>
</div>



<%= render 'layouts/messages'%>

<div class="card">
  <div class="card-horizontal">
    <div class="card-body">
      <h4 class="card-title text-muted">Here are <%= pluralize(@books.count, "book")%> that you may enjoy:</h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
			<% @books.each do |book|%>
        <div class="card mb-3">
          <div class="card-horizontal">
            <div class="img-square-wrapper">
						<%= image_tag(book.image.present? ? book.image.url : 'defaultbook.jpeg', size: '200x200') %> 
              
            </div>
            <div class="card-body">
						
              <h4 class="card-title"> <%= link_to book.title, book_path(book), class:"text-decoration-none text-muted" %></h4>
              <p class="card-text  text-muted ">Author: <%= book.author %></p>
              <p class="card-text  text-muted "> Number of pages: <%= book.number_of_pages %> </p>
              <%= render book.groups%>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Created <%= time_ago_in_words(book.created_at)%> ago</small>
          </div>
        </div>
			<% end %>
		</div>
  </div>
</div>
   

app/views/books/index.html.erb
<div class="nav container-fluid h-100vh">
    <%= signed_in %>
    <h3 class="text-white center-nav"> <%= @user.username%>'s Books</h3>
</div>

<%= render 'layouts/messages'%>

<div class="card">
  <div class="card-horizontal">
    <div class="card-body">
      <h4 class="card-title text-muted">You have read <%= pluralize(@books.count, "book") %>:</h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
			<% @books.each do |book|%>
        <div class="card mb-3">
          <div class="card-horizontal">
            <div class="img-square-wrapper">
						<%= image_tag(book.image.present? ? book.image.url : 'defaultbook.jpeg', size: '200x200') %> 
              
            </div>
            <div class="card-body">
						
              <h4 class="card-title"> <%= link_to book.title, book_path(book), class:"text-decoration-none text-muted" %></h4>
              <p class="card-text  text-muted ">Author: <%= book.author %></p>
              <p class="card-text  text-muted "> Number of pages: <%= book.number_of_pages %> </p>
                <%= render book.groups%>
                
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Created <%= time_ago_in_words(book.created_at)%> ago</small>
          </div>
        </div>
			<% end %>
			<div class="text-center my-5">
				<%= link_to new_book_path, class: 'btn btn-success text-white h3' do %>
					<%= fa_icon "plus" %> Add new Book
				<% end %>
			</div>
		</div>
  </div>
</div>
   

app/views/books/new.html.erb
<div class="nav">
    <%= signed_in %>
    <h2 class="center-nav text-white">Add a new book</h2>
</div>


<div class="col-7 mx-auto py-5">

  <%= render 'layouts/messages'%>


  <%= form_with(model: @book, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder:'Title of Book', class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, placeholder:'Name of Author', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :number_of_pages %>
      <%= f.text_field :number_of_pages, placeholder:'Number of pages', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, placeholder:'Thoughts on this book?', class: 'form-control' %>
    </div>

    <div class="form-group row">
      <%= f.label :groups, class:"col-2 col-form-label"%>
        <div class="col-10 px-0 mx-0">
          <%= f.collection_check_boxes :group_ids, Group.where(user: current_user), :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "mx-3 checkbox  shadow rounded") + cb.text } %>
          <% end %> 
        </div>      
    </div>
  
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <%= f.submit 'Add Book', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="nav">
    <%= signed_in %>
    <h3 class="text-white center-nav"> <%= @book.title%></h3>
    
</div>


<%= render 'layouts/messages'%>
<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
      <div class="card mb-3">
        <div class="card-horizontal">

          <div class="img-square-wrapper">
            <%= image_tag(@book.image.present? ? @book.image.url : 'defaultbook.jpeg', size: '200x200') %> 
          </div>

          <div class="card-body">
          <%= book_user%>
            
            <p class="card-text  text-muted "><strong> Author:</strong> <%= @book.author %></p>
            <p class="card-text  text-muted "> <strong>Number of pages:</strong> <%= @book.number_of_pages %> </p>

              <%= book_group %>
            
          </div>
        </div>
        <div class="card-footer">
            <small class="text-muted">Created <%= time_ago_in_words(@book.created_at)%> ago</small><br>
            <%= book_edit %>
            
            
          </div>
      </div>
    </div>
  </div>
</div>

app/views/books_search/_form.html.erb
<div class ="search">
  <form class="search-form " action='/result' method="get">
    <input class="search-input form-control" type="text" name="search" placeholder="search for book"><br>
    <input class="search-submit btn btn-success" type='submit'>  </input>
  </form>
</div>

app/views/books_search/_multi.html.erb
<% @multi_results.results.work.each do |item| %>
  <div class="card mb-3">
    <div class="card-horizontal">
      <div class="card-body">
        <h4 class="card-text  text-muted ">Title: <%= item.best_book.title %></h4>
        <p class="card-text  text-muted ">Author: <%= item.best_book.author.name %></p>
        <p class="card-text  text-muted ">Year Published: (<%= item.original_publication_year || "N/A" %>)</p>
      </div>
    </div>
  </div>
<% end %>

app/views/books_search/_results.html.erb
<div class="nav container-fluid h-100vh">
  <%= signed_in %>
  <h4 class="text-white center-nav-2"> Showing results for <%= if @search_raw then @search_raw.query end %> from GoodReads</h4>
</div>

<%= render 'layouts/messages'%>

<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
      <%= search_results%>
    </div>
  </div>
</div>

app/views/books_search/_unique.html.erb
<div class="card mb-3">
  <div class="card-horizontal">
    <div class="card-body">
      <h4 class="card-text  text-muted ">Title: <%= @unique_result.results.work.best_book.title %></h4>
      <p class="card-text  text-muted ">Author: <%= @unique_result.results.work.best_book.author.name %></p>
      <p class="card-text  text-muted ">Year Published: (<%= @unique_result.results.work.original_publication_year || "N/A" %>)</p>
    </div>
  </div>
</div>

app/views/books_search/index.html.erb
<div class="nav">
    <%= signed_in %>
    <h3 class="center-nav text-white">Search Books</h3>
</div>

<div class="col-11 mx-5 my-5">
    <%= render 'layouts/messages'%>
    <div class='search-area'>
        <%= render 'form'%>
    </div>
</div>

app/views/groups/_group.html.erb
<%= link_to group.name, group_path(group), class:"badge badge-pill, badge-info mr-1" %>

app/views/groups/index.html.erb
<div class="nav container-fluid h-100vh">
  <%= signed_in %>
  <h3 class="text-white center-nav"> <%= @user.username%>'s Groups</h3>
</div>


<%= render 'layouts/messages'%>

<div class="card">
  <div class="card-horizontal">
    <div class="card-body">
      <h4 class="card-title text-muted">You have created <%= pluralize(@groups.count, "group") %>: </h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 mt-3 text-center">
			<% @groups.each do |group|%>
        <div class="card mb-3">
          <div class="card-horizontal">
            <div class="card-body">
              <h4 class="card-title"> <%= link_to group.name, group_path(group), class:"text-decoration-none text-muted" %></h4>
              <p class="card-text  text-muted "> <strong> Number of books: </strong> <%= group.books.count %> </p>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Created <%= time_ago_in_words(group.created_at)%> ago </small>
          </div>
        </div>
			<% end %>
			<div class="text-center my-5">
				<%= link_to new_group_path, class: 'btn btn-success text-white h3' do %>
					<%= fa_icon "plus" %> Create new Group
        <% end %>
			</div>
		</div>
  </div>
</div>
   

app/views/groups/new.html.erb
<div class="nav">
    <%= signed_in %>
    <h2 class="center-nav text-white">Add a new group</h2>
</div>

<div class="col-7 mx-auto py-5">

  <%= render 'layouts/messages'%>


  <%= form_with(model: @group, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder:'Name of group', class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Add Group', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="nav">
    <%= signed_in %>
    <h3 class="text-white center-nav"> <%= @group.name %></h3>
</div>

<%= render 'layouts/messages'%>
<div class="card">
  <div class="card-horizontal">
    <div class="card-body">
      <h4 class="card-title text-muted">This group has <%= pluralize(@group.books.count, "book") %>: </h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
			<% @books.each do |book|%>
        <div class="card mb-3">
          <div class="card-horizontal">
		        <div class="img-square-wrapper">
						  <%= image_tag(book.image.present? ? book.image.url : 'defaultbook.jpeg', size: '120x120') %> 
            </div>
            <div class="card-body">
              <h4 class="card-title"> <%= link_to book.title, book_path(book), class:"text-decoration-none text-muted" %></h4>
              <p class="card-text  text-muted "> <strong> Title: </strong> <%= book.title %> </p>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Created <%= time_ago_in_words(book.created_at)%> ago </small>
          </div>
        </div>
			<% end %>
		</div>
  </div>
</div>
   

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %> 
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %> 

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to 'BookableApp', root_path, class:"navbar-brand text-white" %>
</nav>

app/views/layouts/_usernav.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to 'BookableApp', root_path, class:"navbar-brand text-white" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to t('.back'), :back, class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "signout", destroy_user_session_path, class:"nav-link text-white", method: :delete  %>
        </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="image" property="og:image" content="https://live.staticflickr.com/65535/50562376467_2285f72e08_z.jpg" />
    <title><%= content_for?(:title) ? yield(:title) : "BookableApp" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
    <body class="grey">

  

    <!-- <div class="container">
      <div class="row">
        <div class="col-lg-9">--> 
      

          <%= yield %>
       <!--  </div>
      </div>/row
    </div> /container -->

  </body>

  
</html>

app/views/users/show.html.erb
<div class=" container-fluid blue h-100vh">
	<%= signed_in %>

	<div class="col-11 mx-5 my-3">
		<%= render 'layouts/messages'%>
	</div>

	<div class=" page-content text-center">
  
		<header class="mt-4 mb-2 py-3  text-white">
			<%= check_avatar(@user)%>
			<h1> <%= @user.username%>'s Profile </h1>
		</header>

		<div class="actions">
			<%= link_to edit_user_registration_path(current_user), class: 'text-white h4' do %>
				<%= fa_icon "cog", class: 'mb-4' %> Account Settings
			<% end %> <br>
			<%= link_to books_path(current_user), class: 'text-white h4' do %>
				<%= fa_icon "book", class: 'mb-4' %> All my Books
			<% end %><br>
			<%= link_to external_path, class: 'text-white h4' do %>
				<%= fa_icon "th-list", class: 'mb-4' %> Books you might like
			<% end %><br>
			<%= link_to new_book_path, class: 'text-white h4' do %>
				<%= fa_icon "plus", class: 'mb-4' %> Add new Book
			<% end %><br>
			<%= link_to groups_path, class: 'text-white h4' do %>
				<%= fa_icon "users", class: 'mb-4' %> Groups
			<% end %><br>
			<%= link_to goodreads_path, class: 'text-white h4' do %>
				<%= fa_icon "search", class: 'mb-4' %> Search Goodreads
			<% end %><br>
		</div>
	</div>
</div>




 

app/views/welcome/index.html.erb
  
<div class="nav">
  <%= render 'layouts/navigation'%>
</div>

<div class="col-11 mx-5 py-3">
	<%= render 'layouts/messages'%>
</div>

<div class="container text-center">
  <h1 class="vertical">Bookable</h1>
  <p> Your bookclub tracking app</p>
    
  <%= link_to 'LOG IN', new_user_session_path, class:"btn btn-primary", id: 'login' %><br>
  <%= link_to 'SIGN UP', new_user_registration_path, class:"btn", id: 'submit'%>
    
</div>